spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}/${DATABASE_DB}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
