spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}/${DATABASE_DB}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    aws:
      endpoint: ${AWS_URL}
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${AWS_REGION}

logging:
  level:
    br:
      com:
        brunno98:
          messagesender:
            inbox: DEBUG