version: "3"

services:
  message-store-service:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=container
      - DATABASE_HOST=db
      - DATABASE_DB=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=pass

  db:
    image: postgres:13.11
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=pass